FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY common/ ./common/
COPY worker/ ./worker/

CMD ["celery", "-A", "worker.main", "worker", "--loglevel=INFO", "--concurrency=2"]
